name: main

on: [push]

jobs:
  build-electron:
    runs-on: ${{ matrix.os.imageName }}

    strategy:
      matrix:
        os:
          - name: windows
            imageName: windows-latest
          - name: linux
            imageName: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: rm -rf build
        shell: bash
      - run: yarn build:${{ matrix.os.name }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os.name }}
          path: build
